// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1AbEz9t7aT1mTO9ohCRSANHVpvDUnx4',
    appId: '1:792461506685:web:288c22d98a4a96e9191914',
    messagingSenderId: '792461506685',
    projectId: 'act17-d60ca',
    authDomain: 'act17-d60ca.firebaseapp.com',
    storageBucket: 'act17-d60ca.firebasestorage.app',
    measurementId: 'G-E65X344JR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTGAX6nLc1IfZXL8GYLg7xlIcy73PP5E',
    appId: '1:792461506685:android:a45437511cfc1826191914',
    messagingSenderId: '792461506685',
    projectId: 'act17-d60ca',
    storageBucket: 'act17-d60ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9riJvRAy2ymbDs73SCG0jccLFG2gbCkA',
    appId: '1:792461506685:ios:9c460db7ca6f9042191914',
    messagingSenderId: '792461506685',
    projectId: 'act17-d60ca',
    storageBucket: 'act17-d60ca.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9riJvRAy2ymbDs73SCG0jccLFG2gbCkA',
    appId: '1:792461506685:ios:9c460db7ca6f9042191914',
    messagingSenderId: '792461506685',
    projectId: 'act17-d60ca',
    storageBucket: 'act17-d60ca.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh1AbEz9t7aT1mTO9ohCRSANHVpvDUnx4',
    appId: '1:792461506685:web:2b76693227966305191914',
    messagingSenderId: '792461506685',
    projectId: 'act17-d60ca',
    authDomain: 'act17-d60ca.firebaseapp.com',
    storageBucket: 'act17-d60ca.firebasestorage.app',
    measurementId: 'G-5W8TWZ9NE0',
  );
}
